/**
 * Rendering the normalized document to disk.
 *
 * Two artefacts, one generation pass, so there is still exactly one source of
 * truth for every repository fact:
 *
 *   data/project-metadata.json    the durable snapshot. Also what the next run
 *                                 falls back to when a repository is
 *                                 unreachable.
 *   src/generated/projectMetadata.ts
 *                                 a typed projection of the same document for
 *                                 the browser build. Never hand-edited; tsc
 *                                 compiles it to js/ like any other source.
 *
 * Both are written deterministically — stable key order, stable event order —
 * so a run that discovers nothing new produces a byte-identical file and the
 * Action makes no commit.
 */

const HEADER = `// AUTO-GENERATED FILE.
// DO NOT EDIT BY HAND.
// Generated by scripts/sync-project-metadata.mjs
//
// Run \`npm run sync:metadata\` locally, or the "Sync project metadata" GitHub
// Action, to refresh it. Curated copy lives in src/data.ts and is never
// overwritten from here.
`;

/** Key order for each project block, so diffs stay readable. */
const PROJECT_KEYS = [
  "repository",
  "repositoryUrl",
  "owner",
  "name",
  "defaultBranch",
  "description",
  "createdAt",
  "pushedAt",
  "commitCount",
  "mergedPullRequestCount",
  "pullRequestCount",
  "latestVersion",
  "latestVersionSource",
  "latestReleaseUrl",
  "latestReleaseDate",
  "languages",
  "generatedTimelineEvents",
  "source",
  "fetchedAt",
];

/**
 * Per-run state that is reported but never published.
 *
 * `stale` and `lastError` describe a run, not a repository. Writing them into
 * the snapshot would mean an outage produces a commit (and a redeploy) that
 * carries no new facts, and a recovery produces a second one to take the marker
 * back out — worse, a project that recovered during a run that wrote for some
 * other reason could keep a `stale: true` that is no longer true. So the
 * markers stay in memory for validation and the run log, and the file on disk
 * only ever contains facts. A GitHub outage therefore changes nothing at all.
 */
const RUN_STATE_KEYS = ["stale", "lastError"];

/**
 * Re-key a document into a stable shape.
 *
 * @param {import("./types.mjs").ProjectMetadataDocument} document
 * @returns {import("./types.mjs").ProjectMetadataDocument}
 */
export function normalizeDocument(document) {
  /** @type {Record<string, any>} */
  const projects = {};
  for (const projectId of Object.keys(document.projects).sort()) {
    const project = document.projects[projectId];
    /** @type {Record<string, any>} */
    const ordered = {};
    for (const key of PROJECT_KEYS) {
      if (project[key] !== undefined) {
        ordered[key] = project[key];
      }
    }
    projects[projectId] = ordered;
  }
  return {
    schemaVersion: document.schemaVersion,
    generatedAt: document.generatedAt,
    projects,
  };
}

/**
 * @param {import("./types.mjs").ProjectMetadataDocument} document
 * @returns {string}
 */
export function renderJson(document) {
  return `${JSON.stringify(normalizeDocument(document), null, 2)}\n`;
}

/**
 * Render the typed TypeScript module.
 *
 * `satisfies` rather than a type annotation keeps the literal types, so a
 * consumer can still narrow on a specific project id, while tsc still checks
 * the shape against GeneratedProjectMetadata.
 *
 * @param {import("./types.mjs").ProjectMetadataDocument} document
 * @returns {string}
 */
export function renderTypeScript(document) {
  const normalized = normalizeDocument(document);
  const body = JSON.stringify(normalized, null, 2)
    .split("\n")
    .map((line, index) => (index === 0 ? line : `${line}`))
    .join("\n");

  return `${HEADER}
import type { GeneratedProjectMetadata } from "../types.js";

export const GENERATED_PROJECT_METADATA: GeneratedProjectMetadata = ${body};
`;
}

/**
 * Whether new output differs from what is already on disk, ignoring only the
 * top-level generatedAt stamp.
 *
 * Without this every scheduled run would commit — the timestamp always moves —
 * and each commit would retrigger the Pages deployment for no change. The
 * per-project `fetchedAt` values are compared, because those moving means real
 * data moved.
 *
 * @param {string|undefined} previousJson
 * @param {import("./types.mjs").ProjectMetadataDocument} next
 * @returns {boolean}
 */
export function hasMeaningfulChange(previousJson, next) {
  if (previousJson === undefined) {
    return true;
  }
  /** @type {any} */
  let previous;
  try {
    previous = JSON.parse(previousJson);
  } catch {
    return true;
  }
  return JSON.stringify(stripVolatile(previous)) !== JSON.stringify(stripVolatile(normalizeDocument(next)));
}

/**
 * @param {any} document
 * @returns {any}
 */
function stripVolatile(document) {
  if (document === null || typeof document !== "object") {
    return document;
  }
  const { generatedAt: _generatedAt, ...rest } = document;
  /** @type {Record<string, any>} */
  const projects = {};
  for (const [projectId, project] of Object.entries(rest.projects ?? {})) {
    if (project === null || typeof project !== "object") continue;
    const { fetchedAt: _fetchedAt, ...projectRest } = /** @type {any} */ (project);
    for (const key of RUN_STATE_KEYS) {
      delete projectRest[key];
    }
    projects[projectId] = projectRest;
  }
  return { ...rest, projects };
}
