/**
 * Rendering the normalized document to disk.
 *
 * Two artefacts, one generation pass, so there is still exactly one source of
 * truth for every repository fact:
 *
 *   data/project-metadata.json    the durable snapshot. Also what the next run
 *                                 falls back to when a repository is
 *                                 unreachable.
 *   src/generated/projectMetadata.ts
 *                                 a typed projection of the same document for
 *                                 the browser build. Never hand-edited; tsc
 *                                 compiles it to js/ like any other source.
 *
 * Both are written deterministically — stable key order, stable event order —
 * so a run that discovers nothing new produces a byte-identical file and the
 * Action makes no commit.
 */

const HEADER = `// AUTO-GENERATED FILE.
// DO NOT EDIT BY HAND.
// Generated by scripts/sync-project-metadata.mjs
//
// Run \`npm run sync:metadata\` locally, or the "Sync project metadata" GitHub
// Action, to refresh it. Curated copy lives in src/data.ts and is never
// overwritten from here.
`;

/** Key order for each project block, so diffs stay readable. */
const PROJECT_KEYS = [
  "repository",
  "repositoryUrl",
  "owner",
  "name",
  "defaultBranch",
  "description",
  "createdAt",
  "pushedAt",
  "commitCount",
  "mergedPullRequestCount",
  "pullRequestCount",
  "latestVersion",
  "latestVersionSource",
  "latestReleaseUrl",
  "latestReleaseDate",
  "languages",
  "generatedTimelineEvents",
  "source",
  "fetchedAt",
];

/**
 * Per-run state that is reported but never published.
 *
 * `stale` and `lastError` describe a run, not a repository. Writing them into
 * the snapshot would mean an outage produces a commit (and a redeploy) that
 * carries no new facts, and a recovery produces a second one to take the marker
 * back out — worse, a project that recovered during a run that wrote for some
 * other reason could keep a `stale: true` that is no longer true. So the
 * markers stay in memory for validation and the run log, and the file on disk
 * only ever contains facts. A GitHub outage therefore changes nothing at all.
 */
const RUN_STATE_KEYS = ["stale", "lastError"];

/**
 * Re-key a document into a stable shape.
 *
 * @param {import("./types.mjs").ProjectMetadataDocument} document
 * @returns {import("./types.mjs").ProjectMetadataDocument}
 */
export function normalizeDocument(document) {
  /** @type {Record<string, any>} */
  const projects = {};
  for (const projectId of Object.keys(document.projects).sort()) {
    const project = document.projects[projectId];
    /** @type {Record<string, any>} */
    const ordered = {};
    for (const key of PROJECT_KEYS) {
      if (project[key] !== undefined) {
        ordered[key] = project[key];
      }
    }
    projects[projectId] = ordered;
  }
  return {
    schemaVersion: document.schemaVersion,
    generatedAt: document.generatedAt,
    projects,
  };
}

/**
 * The browser projection, with full commit bodies removed.
 *
 * Bodies are why this exists. They run to thousands of words each and are only
 * ever read when someone expands a card, so inlining them into the module every
 * page imports made the main bundle several times its own size for data almost
 * nobody requests. They are written to their own file instead and fetched on
 * demand — see renderCommitBodies.
 *
 * @param {import("./types.mjs").ProjectMetadataDocument} document
 * @returns {import("./types.mjs").ProjectMetadataDocument}
 */
function withoutBodies(document) {
  const projects = {};
  for (const [id, project] of Object.entries(document.projects ?? {})) {
    projects[id] = {
      ...project,
      generatedTimelineEvents: (project.generatedTimelineEvents ?? []).map(
        ({ body, ...event }) => event,
      ),
    };
  }
  return { ...document, projects };
}

/**
 * Full commit bodies, keyed by the event identity that names them.
 *
 * Its own artefact so the page bundle stays small: the timeline fetches it the
 * first time a card is expanded, and a visitor who never expands one never
 * downloads it. Sorted by key so a run that discovers nothing new writes a
 * byte-identical file and the Action makes no commit.
 *
 * @param {import("./types.mjs").ProjectMetadataDocument} document
 * @returns {string}
 */
export function renderCommitBodies(document) {
  /** @type {Record<string, string>} */
  const bodies = {};
  for (const project of Object.values(document.projects ?? {})) {
    for (const event of project.generatedTimelineEvents ?? []) {
      if (typeof event.body === "string" && event.body.trim() !== "" && event.identity) {
        bodies[event.identity] = event.body;
      }
    }
  }
  const ordered = Object.fromEntries(
    Object.keys(bodies).sort().map((key) => [key, bodies[key]]),
  );
  return `${JSON.stringify({ schemaVersion: 1, bodies: ordered }, null, 2)}\n`;
}

/**
 * @param {import("./types.mjs").ProjectMetadataDocument} document
 * @returns {string}
 */
export function renderJson(document) {
  return `${JSON.stringify(normalizeDocument(withoutBodies(document)), null, 2)}\n`;
}

/**
 * Render the typed TypeScript module.
 *
 * `satisfies` rather than a type annotation keeps the literal types, so a
 * consumer can still narrow on a specific project id, while tsc still checks
 * the shape against GeneratedProjectMetadata.
 *
 * @param {import("./types.mjs").ProjectMetadataDocument} document
 * @returns {string}
 */
export function renderTypeScript(document) {
  const normalized = normalizeDocument(withoutBodies(document));
  const body = JSON.stringify(normalized, null, 2)
    .split("\n")
    .map((line, index) => (index === 0 ? line : `${line}`))
    .join("\n");

  return `${HEADER}
import type { GeneratedProjectMetadata } from "../types.js";

export const GENERATED_PROJECT_METADATA: GeneratedProjectMetadata = ${body};
`;
}

/**
 * Whether new output differs from what is already on disk, ignoring only the
 * top-level generatedAt stamp.
 *
 * Without this every scheduled run would commit — the timestamp always moves —
 * and each commit would retrigger the Pages deployment for no change. The
 * per-project `fetchedAt` values are compared, because those moving means real
 * data moved.
 *
 * @param {string|undefined} previousJson
 * @param {import("./types.mjs").ProjectMetadataDocument} next
 * @returns {boolean}
 */
export function hasMeaningfulChange(previousJson, next) {
  if (previousJson === undefined) {
    return true;
  }
  /** @type {any} */
  let previous;
  try {
    previous = JSON.parse(previousJson);
  } catch {
    return true;
  }
  return JSON.stringify(stripVolatile(previous)) !== JSON.stringify(stripVolatile(normalizeDocument(next)));
}

/**
 * Whether the generated TypeScript module on disk still matches what this
 * document would render.
 *
 * Checked separately from the JSON because the two files can diverge: the
 * module can be deleted, half-written, or hand-edited while the snapshot stays
 * current. Comparing only the JSON would then report "no change" and leave the
 * module broken, so `tsc` fails on every later run with nothing repairing it.
 *
 * The run stamps are blanked on both sides, which keeps the outage guarantee
 * intact — a run that finds nothing new still renders an identical module.
 *
 * @param {string|undefined} previousTs
 * @param {import("./types.mjs").ProjectMetadataDocument} next
 * @returns {boolean}
 */
export function hasGeneratedDrift(previousTs, next) {
  if (previousTs === undefined) {
    return true;
  }
  return blankStamps(previousTs) !== blankStamps(renderTypeScript(next));
}

/**
 * @param {string} text
 * @returns {string}
 */
function blankStamps(text) {
  return text.replace(/"(generatedAt|fetchedAt)": "[^"]*"/g, '"$1": "<stamp>"');
}

/**
 * @param {any} document
 * @returns {any}
 */
function stripVolatile(document) {
  if (document === null || typeof document !== "object") {
    return document;
  }
  const { generatedAt: _generatedAt, ...rest } = document;
  /** @type {Record<string, any>} */
  const projects = {};
  for (const [projectId, project] of Object.entries(rest.projects ?? {})) {
    if (project === null || typeof project !== "object") continue;
    const { fetchedAt: _fetchedAt, ...projectRest } = /** @type {any} */ (project);
    for (const key of RUN_STATE_KEYS) {
      delete projectRest[key];
    }
    projects[projectId] = projectRest;
  }
  return { ...rest, projects };
}
