import type { PortfolioData } from "./types.js";

export const PORTFOLIO: PortfolioData = {
  compiled: "2026-09-11",
  source: "Public git history and merged pull requests on github.com/BPForbes",
  projects: {
    emr: "Electronic medical record",
    "homework-central": "Homework Central",
    flinstone: "Flinstone Kernel",
    keyquorum: "KeyQuorum",
    qpu: "QPU",
    "flinstone-os": "Flinstone-OS",
  },
  projectOrder: [
    "emr",
    "flinstone-os",
    "qpu",
    "flinstone",
    "homework-central",
    "keyquorum",
  ],
  languages: {
    emr: [
      { name: "Kotlin", pct: 40, color: "#A97BFF" },
      { name: "Java", pct: 35, color: "#b07219" },
      { name: "Firebase / REST", pct: 25, color: "#FFA000" },
    ],
    "homework-central": [
      { name: "C#", pct: 59, color: "#512bd4" },
      { name: "TypeScript", pct: 26, color: "#3178c6" },
      { name: "CSS", pct: 8, color: "#c98a4a" },
      { name: "Shell", pct: 7, color: "#7ea36a" },
    ],
    flinstone: [
      { name: "C", pct: 83, color: "#555555" },
      { name: "Shell", pct: 6, color: "#7ea36a" },
      { name: "Assembly", pct: 5, color: "#c98a4a" },
      { name: "Python / C++", pct: 6, color: "#3178c6" },
    ],
    keyquorum: [{ name: "Rust", pct: 100, color: "#dea584" }],
    qpu: [
      { name: "TypeScript", pct: 82, color: "#3178c6" },
      { name: "Python", pct: 18, color: "#3572a5" },
    ],
  },
  events: [
    {
      date: "2021-08",
      kind: "release",
      project: "emr",
      title: "Planning and proof of concept",
      detail: "Engagement opens for an organization serving 26 hospital locations. August is planning and a PoC: scope Kotlin patient services, Java staff APIs, Firebase, and the move off spreadsheet workflows.",
    },
    {
      date: "2021-10",
      kind: "feature",
      project: "emr",
      title: "Initial front end",
      detail: "September–October: first client-facing UI, including login and the screens that sit on top of the PoC.",
    },
    {
      date: "2021-12",
      kind: "feature",
      project: "emr",
      title: "Client full stack",
      detail: "Remainder of 2021 is client-based end-to-end work — PPI and patient workflow records, Firebase persistence, and Kotlin patient services — rather than staff operations.",
    },
    {
      date: "2022-02",
      kind: "feature",
      project: "emr",
      title: "Staff-side services",
      detail: "January–February is primarily staff-based: Java staff endpoints, credentials, and the operational side of the record system.",
    },
    {
      date: "2022-03",
      kind: "feature",
      project: "emr",
      title: "Wiring client and staff",
      detail: "March into April connects the two stacks: client/patient flows and staff credentials share the same records and permissions.",
    },
    {
      date: "2022-04",
      kind: "feature",
      project: "emr",
      title: "HIPAA drill and hardening",
      detail: "Security and documentation ran the whole engagement; April is when HIPAA was drilled in earnest. April–May concentrates on securing paths, backups, and automated checks.",
    },
    {
      date: "2022-05",
      kind: "release",
      project: "emr",
      title: "Sponsor handoff",
      detail: "May closes securing and transfers administrative ownership after onboarding. Team measured about 60% improvement in record-processing efficiency versus the spreadsheet baseline.",
    },
    {
      date: "2025-05-28",
      kind: "release",
      project: "flinstone",
      title: "Flinstone repository created",
      detail: "Bailey-Forbes-Flinstone starts as a C filesystem and shell with hardware-level disk operations. This becomes the long-running kernel line.",
      href: "https://github.com/BPForbes/Bailey-Forbes-Flinstone",
    },
    {
      date: "2025-07-07",
      kind: "release",
      project: "flinstone-os",
      title: "Flinstone-OS toy kernel",
      detail: "C++/Assembly experiment with Ethernet/UDP headers, a minimal TCP/IP stack, libsodium, and QEMU/VirtualBox simulation scripts.",
      href: "https://github.com/BPForbes/Flinstone-OS",
    },
    {
      date: "2025-07-10",
      kind: "release",
      project: "qpu",
      title: "QPU Python simulator",
      detail: "Universal Quantum Processor lands: assembly-style AST, cycle clock, process compilation, and full-adder protocols (1-, 2-, 4-, then 8-bit).",
      href: "https://github.com/BPForbes/QPU",
    },
    {
      date: "2025-07-22",
      kind: "feature",
      project: "qpu",
      title: "Statevector backend and noise",
      detail: "PR #16 adds a qubit statevector engine, noise channels, ID locking per process, and Hilbert-space logging.",
    },
    {
      date: "2025-09",
      kind: "feature",
      project: "homework-central",
      title: "Baker Hill internship",
      detail: "C#/.NET and TypeScript production work on loan-origination systems. NuComply integration is separated from HTTP transport and cut from months to days.",
    },
    {
      date: "2026-02-14",
      kind: "feature",
      project: "flinstone",
      title: "OS transformation wave",
      detail: "ASM memory layer, design-pattern file manager, drivers, thread-safe allocator, embedded x86 VM, MLQ scheduler, and unified x86-64/AArch64 driver API.",
    },
    {
      date: "2026-04-12",
      kind: "feature",
      project: "flinstone",
      title: "Memory-safety and bare-metal pass",
      detail: "Six memory-safety bugs closed; layered driver model and architecture checks land on develop/main.",
    },
    {
      date: "2026-05-07",
      kind: "feature",
      project: "flinstone",
      title: "WebAssembly host",
      detail: "Emscripten build embeds the VM in-page, with async stdin and interactive-mode fixes.",
    },
    {
      date: "2026-05-11",
      kind: "release",
      project: "flinstone",
      title: "2.2.4 → 3.2.0 version train",
      detail: "Semver lock files, FAT32 host volumes, AArch64 Makefile defaults for Raspberry Pi, FAT32-backed shell history, and cursor editing.",
    },
    {
      date: "2026-05-12",
      kind: "release",
      project: "flinstone",
      title: "3.3.0 contracts, jail, audit",
      detail: "Versioned subsystem contracts, fs_jail discipline, and a post-exec audit log split from FL1 command history.",
    },
    {
      date: "2026-05-18",
      kind: "release",
      project: "flinstone",
      title: "4.0.0 system contracts",
      detail: "Major release: inheritable P0–P9 contracts for foundations, runtime, identity, networking, drivers, storage, observability, operations, virtualization, and hardening.",
    },
    {
      date: "2026-05-19",
      kind: "release",
      project: "flinstone",
      title: "4.0.1 host hardening",
      detail: "Serial Makefile default, IPC errno semantics, VFS/FAT32 overflow guards, shell pool lifecycle, and PIC EOI fixes.",
    },
    {
      date: "2026-05-23",
      kind: "release",
      project: "flinstone",
      title: "4.1.0 identity and auth",
      detail: "SQLite user_db, PBKDF2 passwords, login/su/sudo, elevation pool, fs_jail elevation checks, and P0–P2 integration.",
    },
    {
      date: "2026-05-24",
      kind: "release",
      project: "flinstone",
      title: "4.1.1 issue sweep",
      detail: "GM=1 BUILD 3 closes GitHub issues #169–#222: ARM ABI, session hardening, batch argv clamps, SHA-256 dep fetches, threadpool OOM paths.",
    },
    {
      date: "2026-06-07",
      kind: "release",
      project: "homework-central",
      title: "Homework Central repository",
      detail: "Public repo opens for a purpose-built replacement of a 16,000-member Discord community.",
      href: "https://github.com/BPForbes/Homework-Central",
    },
    {
      date: "2026-06-08",
      kind: "release",
      project: "qpu",
      title: "QPU browser workbench",
      detail: "BPForbes.QPU.github.io (moved from BPForbes.github.io) ships a TypeScript/React circuit workbench: AST compiler, hamburger file tools, .qpucir storage, and PDF docs on Pages.",
      href: "https://github.com/BPForbes/BPForbes.QPU.github.io",
    },
    {
      date: "2026-06-09",
      kind: "feature",
      project: "qpu",
      title: "Circuit Correction Lab",
      detail: "Truth-table module tests, local Ollama correction, catalog downloads, and later partial truth tables plus a custom-gate engine.",
    },
    {
      date: "2026-06-19",
      kind: "release",
      project: "flinstone",
      title: "4.2.0 P3 networking",
      detail: "netdev, TAP, ARP, IPv4/IPv6, UDP/TCP shims, DNS, DHCP, Wi-Fi station, multi-device chat server, and WSL/Linux hosting. Latest GM main promote.",
    },
    {
      date: "2026-06-20",
      kind: "feature",
      project: "flinstone",
      title: "Wi-Fi drivers and 802.11ax",
      detail: "v4.3.0 train: Wi-Fi drivers, home SSID join, LAN/WLAN hosting, macvlan identity, and later Dragonfly SAE (WPA3) OTA connect.",
    },
    {
      date: "2026-06-27",
      kind: "feature",
      project: "homework-central",
      title: "Login and RBAC",
      detail: "PR #3: React/C# login with a role-based permission model. PR #4 the next day encodes permissions as bitmasks.",
    },
    {
      date: "2026-06-28",
      kind: "feature",
      project: "homework-central",
      title: "One-command Docker stack",
      detail: "run-dev scripts start Postgres, FCaptcha, the ASP.NET API, and the Vite frontend. Visual Studio F5 integration follows.",
    },
    {
      date: "2026-06-30",
      kind: "feature",
      project: "homework-central",
      title: ".NET 10 and tenant isolation",
      detail: "Upgrade to .NET 10.0.301, GitHub Actions CI, and per-developer tenant databases for /devlogin.",
    },
    {
      date: "2026-07-01",
      kind: "feature",
      project: "homework-central",
      title: "Chat rooms and visibility",
      detail: "Resource visibility primitive and chat-room access model (issue #10 / PR #12). Typing, reconnect, and seed-gate fixes land the same week.",
    },
    {
      date: "2026-07-04",
      kind: "feature",
      project: "homework-central",
      title: "Captcha and self-serve roles",
      detail: "Signup/dashboard FCaptcha verification and a Get Roles room. Docker image builds are optimized.",
    },
    {
      date: "2026-07-08",
      kind: "feature",
      project: "homework-central",
      title: "Mentions, inbox, custom roles",
      detail: "Mentions with cooldowns, inbox bulk delete, role colors, @ autocomplete, and infrastructure permission fixes.",
    },
    {
      date: "2026-07-15",
      kind: "feature",
      project: "homework-central",
      title: "Water-theme UI redesign",
      detail: "Persistent navigation, admin rail, custom channels, and a Preview editor gate rebase onto main (#47).",
    },
    {
      date: "2026-07-16",
      kind: "feature",
      project: "homework-central",
      title: "Tickets, media, Trial Tutor",
      detail: "PR #50 adds moderation tickets, media, votes, Trial Tutor, and an assessment pipeline — the Discord-replacement surface.",
    },
    {
      date: "2026-07-21",
      kind: "feature",
      project: "homework-central",
      title: "Moderation neural net",
      detail: "CPU ChatMonitor models, tutor subject processor, concurrent ticket generation, and training-session removal. Resume cites 35,600+ trainable weights.",
    },
    {
      date: "2026-07-23",
      kind: "feature",
      project: "homework-central",
      title: "2D neural mesh and faster training",
      detail: "Mesh slices, worker projection, Kubernetes training/viz split, and fewer LLM round-trips for synthetic sessions.",
    },
    {
      date: "2026-08-05",
      kind: "feature",
      project: "homework-central",
      title: "Live audit and weight UX",
      detail: "Single training LLM per NN session, live audit/weight UI, plus CodeQL and OOM fixes.",
    },
    {
      date: "2026-08-24",
      kind: "release",
      project: "keyquorum",
      title: "KeyQuorum scaffolding",
      detail: "SQLite schema, password manager, expiring share links, password-locked files, then a hardened CLI the same day.",
      href: "https://github.com/BPForbes/KeyQuorum",
    },
    {
      date: "2026-08-25",
      kind: "feature",
      project: "keyquorum",
      title: "Hardware-key registry and recursive splits",
      detail: "Key generation/register, M-of-N trees, signature verification, export bundles, PIN unlock windows.",
    },
    {
      date: "2026-08-30",
      kind: "feature",
      project: "keyquorum",
      title: "Arena tree and bridges",
      detail: "LCA reconstruct, cross-branch bridges, PSS eviction, then private sign bridges across independent stores.",
    },
    {
      date: "2026-09-01",
      kind: "feature",
      project: "keyquorum",
      title: "Mailbox relay",
      detail: "Axum mailbox with API keys is introduced, reverted, then re-landed with hardened merge, URL, and store integrity checks.",
    },
    {
      date: "2026-09-02",
      kind: "feature",
      project: "keyquorum",
      title: "Provider trust and TTL",
      detail: "Date-based TTL for files, signed provider certificates, and a decision to drop network presence checks from the product.",
    },
    {
      date: "2026-09-08",
      kind: "feature",
      project: "homework-central",
      title: "Training pause and DevOps gates",
      detail: "Continuous training can pause without resetting the ticket cursor. DevOps thought files and CodeRabbit CLI gates land around it.",
    },
  ],
};
