name: Typecheck

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Test metadata generator
        run: npm run test:metadata
      - name: Compile TypeScript
        run: npm run build
